# Site settings
title: Jaewoo Blog
description: 'ssafy에서 배운 걸 정리해 봅시다'
url: 'https://jaewoo-lee.github.io/'
baseurl: 
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Jaewoo Lee'
  email: ashilso29@gmail.com
  twitter_username: 
  facebook_username: jaewoo.lee.10
  github_username:  Jaewoo-Lee
  linkedin_username:  jaewoo317

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
